# https://wiki.hyprland.org/Nvidia/#environment-variables
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# https://wiki.hyprland.org/Nvidia/#va-api-hardware-video-acceleration
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto


# nvidia firefox (for hardware acceleration on FF)?
# check this post https://github.com/elFarto/nvidia-vaapi-driver#configuration
env = MOZ_DISABLE_RDD_SANDBOX,1
env = EGL_PLATFORM,wayland

# fix laggy cursor
cursor {
    no_hardware_cursors = true
}
